### ISSUE TITLE
Working version available?

### ISSUE THREAD

**Issue by PieWol** [encryptogroup/LEAKER#5]
Hey there,
I'm interested in playing around with this framework but somehow out of the box this project doesn't seem runnable. I can't execute the example script with the package versions listed in the requirements file. So I'm asking if there is a better maintained version which works out of the box?

**Comment by PieWol** [comment]
Basically if I run ``pip install -r requirements.txt`` it defaults to the latest available version which by then has deprecated a ton of used functions. @patrickehrler 

see
```
/LEAKER/venv/lib/python3.8/site-packages/tikzplotlib/_color.py", line 32, in _get_closest_colour_name
    for h, name in webcolors.CSS3_HEX_TO_NAMES.items():
AttributeError: module 'webcolors' has no attribute 'CSS3_HEX_TO_NAMES'
```

**Comment by atreiber94** [comment]
Yeah, unfortunately the framework is not being maintained to work with the latest available versions, mostly because it relies on some libraries that themselves are no longer maintained (like `tikzplotlib`). You could try to install the exact versions listed in `requirements.txt`, it does work with those and Python 3.8.

If the issues largely stem from `tikzplotlib` you could also avoid this being imported by not specifying any output plot files

**Comment by PieWol** [comment]
Great, thanks :)
